### ISSUE TITLE
“Prompt Separate Line” line wrap bug

### ISSUE THREAD

**Issue by dangodev** [caiogondim/bullet-train.zsh#178] opened 2016-11-14 22:23 UTC
If I set `BULLETTRAIN_PROMPT_SEPARATE_LINE=false` in my `.zshrc` config, and if the command wraps to the next line due to a long command, the first line disappears. There are other obvious display issues caused from command wrapping to the next line.

**Comment by vadviktor** [comment] 2017-02-13 08:37
We would need to know which OS/terminal are you using to be able to reproduce if any of us have access to the same setup. Sadly I only have access to Ubuntu/Arch linux and e.g. Konsole has no issues with this feature.

**Comment by dangodev** [comment] 2017-03-14 13:33
Good catch—it actually only seems to be an issue with MacOS and iTerm, which was what I was using when reporting the bug. I’m not noticing the bug with [Hyper](https://hyper.is/) or stock Terminal.

**Comment by vadviktor** [comment] 2017-03-22 07:59
Since it sounds like a "MacOS and iTerm" issue, I myself cannot help to debug this.

As a side note, I start to wonder if these line wrapping/rendering bugs are present because of the unicode char mapping nature of this theme.

@dawikur @caiogondim can any of you verify this bug happening?

**Comment by dawikur** [comment] 2017-03-22 08:26
@vadviktor I am using Archlinux, never saw this problem.

**Comment by vadviktor** [comment] 2017-08-07 11:35
Closing now as we don't know how to replicate and probably is a bug in a not so sophisticated terminal.

**Closed by vadviktor** 2017-08-07 11:35 UTC
Labels: bug
